version: '3.1'
services:

  tp-achat:
    container_name: achat
    image: "backend_achat"
    build: .
    networks:
      - test_default   
    ports:
      - "8089:8089"
    environment: # Pass environment variables to the service
      - SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tpachato?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - MYSQL_HOST=tp-achat-mysql
      - MYSQL_USERNAME=cheima
      - MYSQL_PASSWORD=cheima
      - MYSQL_DATABASE=tpachato
    
    depends_on:
      - tp-achat-mysql

  tp-achat-mysql:
    container_name: achat-mysql_2
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=cheima
      - MYSQL_DATABASE=achat
      - MYSQL_USER=cheima
      - MYSQL_PASSWORD=cheima
    ports:
      - 3307:3306
    volumes:
      - tp-achat-mysql-vol:/my/own/datadir       
    networks:
      - test_default   

   

volumes:
  tp-achat-mysql-vol:
networks:
  test_default:
